version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: jeevan
      POSTGRES_PASSWORD: G1@4424
      POSTGRES_DB: jeevanDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/jeevanDB
      DB_USER: jeevan
      DB_PASSWORD: G1@4424
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "3000:80" # Serving the React app on port 80 of the container
    environment:
      REACT_APP_API_URL: http://backend:8080  # Connecting to backend via service name
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
