ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: "jdbc:postgresql://postgres:5432/jeevanDB"
  user: jeevan
  password: G1@4424